### PR TITLE
Split shims from workspace

### PR DESCRIPTION
**Pull request by ipuustin**
Move the shims binaries to separate dependency management. This it not a fully good thing, because it increases the manual effort needed for dependency management. The positive side is that it removes conflicts between wasmedge and wasmtime dependencies. Note that `cargo build` no longer builds the shims -- you need to use `make build` for that.

Fixes: https://github.com/containerd/runwasi/issues/72

### CODE REVIEW

**Comment by Mossaka** [comment]
Isn't the only conflicted dependency, shared by both wasmedge and wasmtime, `wasmtime-fiber` has been pinned by PR #87? Thus we don't really need to split them into two shims from the workspace anymore. I guess we still might ran into the dependency conflicts problem in the future.

**Comment by ipuustin** [comment]
Yeah, as long as we don't use `async` feature in wasmtime, things will work for now. However I think we'll eventually hit more snags like this, especially if we add new runtimes with new deps to the repository. I think this boils down to how we want to organize the repo -- I see three options:

1. Separate crates for shims (this PR). Downside is more manual work updating the deps. Also if the runwasi lib deps start to conflict with shim runtime deps, then this doesn't help with that.
2. Solving the dependency problems one-by-one when they appear (current model). This might become easier or more difficult when we move to libcontainer. This may also require that we work with the runtime lib projects to keep them in sync? 
3. Separate git repos and thus different workspaces for the different shims to keep the dependencies separate. The benefit would be that in the future the shims could have their release cycles detached from runwasi release cycle. The downside would be a lot more tricky API management and the added complexity in code and repository management.

**Comment by cpuguy83** [comment]
> The benefit would be that in the future the shims could have their release cycles detached from runwasi release cycle

This one we already have separate since we are namespacing tags per crate as described in https://github.com/containerd/runwasi/blob/main/RELEASE.md

That said, I don't think it would be horrible to split up the workspace if we end up having more problems.

I think for the wasmtime-fiber issue we should probably talk to the wasmtime folks about this:

https://github.com/bytecodealliance/wasmtime/blob/13be5618a7fce47ae1069be011979538fe7809db/crates/fiber/Cargo.toml#L10-L14

```
# We link to some native code with symbols that don't change often, so let Cargo
# know that we can't show up multiple times in a crate graph. If this is an
# issue in the future we should tweak the build script to set `#define`
# directives or similar to embed a version number of this crate in symbols.
```

**Comment by cpuguy83** [comment]
Opened https://github.com/bytecodealliance/wasmtime/issues/6083 to discuss this.

**Comment by ipuustin** [comment]
Closing this (at least for now).

**Pull request closed without merging**
