### PR TITLE
Merge both existing `run_wasi_test` implementations

### PR DESCRIPTION
**Pull request by jprendes**
Small cleanup deduplicating code.

### CODE REVIEW

**Review by Mossaka — DISMISSED** [review]
LGTM! Love the use of generics

**Comment by jsturtevant** [comment]
nice, this is similar to what I tried in https://github.com/containerd/runwasi/pull/220 but cleaner after the clean up to the instance and engine traits.

This function could be used to help with https://github.com/containerd/runwasi/pull/111 as well.

**Comment by jprendes** [comment]
> Love the use of generics

Otherwise I wold have had to move `tempfile` to a full `dependency` instead of a `dev-dependency` :-)

**Comment by jprendes** [comment]
green CI now :-)

**Review by Mossaka — APPROVED** [review]

**Pull request merged**
