### PR TITLE
rust-toolchain: bump rust to 1.81.0

### PR DESCRIPTION
**Pull request by Mossaka**
bumps rust compiler to the latest version

### CODE REVIEW

**Review by jprendes — APPROVED** [review]
LGTM

**Comment by jprendes** [comment]
Looks like we should be able to bump to 1.81, as that's what wasmer is using.

**Review by jprendes — APPROVED** [review]
LGTM

**Comment by Mossaka** [comment]
I would love to have the Wasmer maintainers to maintain this shim. CC @dierbei

**Comment by jprendes** [comment]
@andreiltd has been doing some work to get the wasmer shim in shape.
He made a PR in wasmer to fix the wasmparser dependency conflict, and it got merged, but hasn't been released yet.
Maybe we can switch to a git dependency like we do in wamr?

**Comment by Mossaka** [comment]
Okay I will close this PR in favor of #730

**Pull request closed without merging**
