### PR TITLE
Add tests for k8s and fix cgroup issue

### PR DESCRIPTION
**Pull request by cpuguy83**
See individual commits for descriptions.

### CODE REVIEW

**Review by devigned — APPROVED** [review]
lgtm!

**Comment by Mossaka** [comment]
Is this PR solving issue #40 ?

**Comment by cpuguy83** [comment]
No this only solves a cgroupv2 issue.

I need to work out how to test both cgroupv1 and cgroupv2 since this is entirely dependent on the node the tests are running on.
Probably I will just spin up a VM in qemu.

**Review by Mossaka — APPROVED** [review]
lgtm!

**Pull request merged**
