### PR TITLE
wasmedge: test for exit with a trap.

### PR DESCRIPTION
**Pull request by ipuustin**
Test for WasmEdge error exit codes.

### CODE REVIEW

**Comment by ipuustin** [comment]
Needed to add serial_test crate to solve the stdout race condition.

**Review by Mossaka — APPROVED** [review]
lgtm!

**Comment by cpuguy83** [comment]
Can you sign off all your commits?

**Comment by ipuustin** [comment]
Btw, I tried out if I could get something like this to work to get real exit codes from the child process:

```diff
diff --git a/crates/wasmedge/src/instance.rs b/crates/wasmedge/src/instance.rs
index dd15de5..4241df2 100644
--- a/crates/wasmedge/src/instance.rs
+++ b/crates/wasmedge/src/instance.rs
@@ -197,7 +197,7 @@ impl Instance for Wasi {
         debug!("call prehook before the start");
         oci::setup_prestart_hooks(&spec.hooks())?;

-        let vm = prepare_module(engine.clone(), &spec, stdin, stdout, stderr)
+        let mut vm = prepare_module(engine.clone(), &spec, stdin, stdout, stderr)
             .map_err(|e| Error::Others(format!("error setting up module: {}", e)))?;

         let cg = oci::get_cgroup(&spec)?;
@@ -235,12 +235,17 @@ impl Instance for Wasi {
             }
             exec::Context::Child => {
                 // child process
-
-                // TODO: How to get exit code?
-                // This was relatively straight forward in go, but wasi and wasmtime are totally separate things in rust.
                 let _ret = match vm.run_func(Some("main"), "_start", params!()) {
                     Ok(_) => std::process::exit(0),
-                    Err(_) => std::process::exit(137),
+                    Err(_) => {
+                        let wasi_instance = vm.wasi_module().unwrap();
+                        let exit_code = wasi_instance.exit_code();
+                        if exit_code == 0 || exit_code > 255 {
+                            // 0 is reserved for success and > 255 aren't supported by Linux.
+                            std::process::exit(137);
+                        }
+                        std::process::exit(exit_code as i32);
+                    }
                 };
             }
         }
```

However, this doesn't seem to work: in the error branch, the `exit_code()` function appears to always return `0`. I think this is exactly the wrong error value since that would indicate a successful exit.

**Review by cpuguy83 — APPROVED** [review]

**Pull request merged**
