### PR TITLE
More publishing cleanup

### PR DESCRIPTION
**Pull request by cpuguy83**
- Rename shim crates
- Change release pipeline to look for `<crate>/<version>` tags and only build releases for individual crates
- Add dockerfile/bake targets for building release tarballs.

Test run: https://github.com/cpuguy83/runwasi-fork/actions/runs/4316874936
Result: ~~https://github.com/cpuguy83/runwasi-fork/releases/tag/containerd-shim-wasmtime%2Fv0.2.0-beta.0~~ Temporarily not available as I accidentally deleted this release while testing some other changes

### CODE REVIEW

**Comment by cpuguy83** [comment]
@rumpl

**Review by devigned — COMMENTED** [review]
The workflows look great. The only feedback I have is that there are a lot of warnings generated about Node.js 12 and `set-output` being used. I think quite a few of them are related to: https://github.com/actions-rs/toolchain/issues/221. Based on that thread, it looks like that action isn't actively maintained. Perhaps, it would be better to run `rustup` rather than that action.

**Review by Mossaka — APPROVED** [review]
lgtm! 

Before we publish, do we want to split wasmtime and wasmedge binaries to their own workspaces so that they don't share dependencies as discussed in #72?

**Comment by cpuguy83** [comment]
Yeah we can hold a release to tie up any loose ends, though I'm not sure it's worh waiting to split those (and maybe not even necessary to do so since the crate's cargo.toml can specific whatever deps they want, including inheriting from the workspace).

**Comment by cpuguy83** [comment]
Note, I'm going to be pushing up some more changes here to get rid of actions-rs and also use the `gh` cli to publish releases.

**Comment by cpuguy83** [comment]
And here we go: https://github.com/cpuguy83/runwasi-fork/releases/tag/containerd-shim-wasmtime%2Fv0.2.0-beta.2
https://github.com/cpuguy83/runwasi-fork/actions/runs/4326517018

**Comment by cpuguy83** [comment]
@rumpl Can you check that this works for what you may need it for?

**Comment by devigned** [comment]
> And here we go: https://github.com/cpuguy83/runwasi-fork/releases/tag/containerd-shim-wasmtime%2Fv0.2.0-beta.2
> https://github.com/cpuguy83/runwasi-fork/actions/runs/4326517018

So clean!!

**Review by devigned — APPROVED** [review]
lgtm!

**Review by rumpl — APPROVED** [review]
The wastime release you linked works for me, does this work for wasmedge too?

**Comment by cpuguy83** [comment]
It does, but apparently my conditional for installing the wasmedge stuff isn't working as expected.
Let me fix that up.

**Comment by cpuguy83** [comment]
Fixed https://github.com/cpuguy83/runwasi-fork/actions/runs/4346827066
https://github.com/cpuguy83/runwasi-fork/releases/tag/containerd-shim-wasmedge%2Fv0.2.0-beta.0

**Comment by rumpl** [comment]
Looking great, thanks!

**Pull request merged**
