### PR TITLE
add wasmer doc

### LINKED ISSUE #301: Add documentation for wasmer
Add documentation for wasmer. Make it easier for others.

Here is an example：
https://github.com/containerd/runwasi/blob/e1f9e925cf283437f3445a68e552c2d2124c0e9b/README.md?plain=1#L116-L143
https://github.com/containerd/runwasi/blob/e1f9e925cf283437f3445a68e552c2d2124c0e9b/README.md?plain=1#L233-L256

### PR DESCRIPTION
**Pull request by dierbei**
add wasmer doc

Fix #301

### CODE REVIEW

**Comment by jsturtevant** [comment]
are there any pre-reqs that need to be installed with wasmer? otherwise lgtm

**Review by Mossaka — APPROVED** [review]

**Comment by dierbei** [comment]
> are there any pre-reqs that need to be installed with wasmer? otherwise lgtm

Thanks for the tip, I seem to have forgotten about this.

I decided to go ahead and test it, without the wasmer installed.

**Comment by dierbei** [comment]
@jsturtevant No other dependencies are required after testing.

**Comment by jsturtevant** [comment]
LGTM

**Review by jprendes — APPROVED** [review]
LGTM

**Comment by jprendes** [comment]
@devigned PTAL

**Pull request merged**
