### PR TITLE
Update project to latest shim-protos and ttrpc using protobuf 3.x

### PR DESCRIPTION
**Pull request by jsturtevant**
In preparation for adding windows #49 which is built using latest [ttrpc libraries](https://github.com/containerd/ttrpc-rust/pull/172) which use protobuf 3, this PR updates the project to use latest dependencies and moves the protocols to using protobuf 3.  

note:  There isn't a release of the [shim-protos](https://github.com/containerd/rust-extensions/blob/main/crates/shim-protos/Cargo.toml) project with these changes yet so it pins a rev.  I am going to open an issue on https://github.com/containerd/rust-extensions/ to see if we can get a release (or maybe wait till the windows changes propagate up). Opened this up to show required changes which allow for using Windows.

### CODE REVIEW

**Comment by jsturtevant** [comment]
This is taking much longer than anticipated, things are moving along but slowly.  I am finding it difficult to maintain this patch and work on the Windows implementation with the various changes going in for the youki work. 

Any thoughts on pinning to a rev vs a realse so we can start bumping the other dependencies and moving forward on protobuf 3?

**Comment by devigned** [comment]
> This is taking much longer than anticipated, things are moving along but slowly. I am finding it difficult to maintain this patch and work on the Windows implementation with the various changes going in for the youki work.
> 
> Any thoughts on pinning to a rev vs a realse so we can start bumping the other dependencies and moving forward on protobuf 3?

I'm good with pinning to a rev as long as we have an issue to track the follow up work. What do others think?

**Comment by jsturtevant** [comment]
> I'm good with pinning to a rev as long as we have an issue to track the follow up work. What do others think?

I've refreshed the PR and opened https://github.com/containerd/runwasi/issues/162 to track updating getting this on a release

**Review by cpuguy83 — APPROVED** [review]

**Pull request merged**
