### PR TITLE
refactor: use collect_metrics

### PR DESCRIPTION
**Pull request by vyta**
Took a stab at issue #229

### CODE REVIEW

**Comment by Mossaka** [comment]
Hey thanks for contributing!

There is a recent PR https://github.com/containerd/rust-extensions/pull/163 that merged in to `containerd-shim` but I don't think it's released as part of `0.4.0`. This PR supports metric in cgroups v2. 

Hence I'd like to pause this PR until we got a new release of the containerd-shim.

**Comment by jsturtevant** [comment]
@vyta you could modify the cargo.toml at https://github.com/containerd/runwasi/blob/6287dff637b0ac96a43a6bbe2c7919f8b2f2cf27/Cargo.toml#L26

to point to the 

```
containerd-shim = { git = 'https://github.com/containerd/rust-extensions', rev= 'latestcommit' }
```

so you could get the code ready for the release

**Comment by jsturtevant** [comment]
awesome! looks like this is passing tests, the failure is #252 I believe

Once we get a release of rust-extensions we can remove the revision number from this PR.

**Review by cpuguy83 — DISMISSED** [review]

**Comment by Mossaka** [comment]
Need a rebase

**Review by Mossaka — APPROVED** [review]

**Comment by vyta** [comment]
@Mossaka @jsturtevant After rebasing, I am noticing that I'm no longer seeing metrics for `cpuacct.usage`, mem and PIDS ok though. Not sure if this is just an issue I'm seeing w/ my containerd setup or something else?

**Comment by Mossaka** [comment]
Are you in cgroups v2 or v1

**Comment by vyta** [comment]
> Are you in cgroups v2 or v1

v1

**Comment by jsturtevant** [comment]
hmm I wonder if this is due to not having `cgroups-rs = "0.3.3"` (https://github.com/containerd/rust-extensions/pull/169 hasn't merged as some manual changes are required

**Comment by vyta** [comment]
> hmm I wonder if this is due to not having `cgroups-rs = "0.3.3"` ([containerd/rust-extensions#169](https://github.com/containerd/rust-extensions/pull/169) hasn't merged as some manual changes are required

I did try with `cgroups-rs = "0.3.3"` also, and had the same result

**Comment by Mossaka** [comment]
That might be a bug from my implementation of the `collect_metrics` as I didn't do enough testing on cgroups v1 case. I will try to reproduce it from upstream. It shouldn't block this PR though.

**Comment by jsturtevant** [comment]
> Once we get a release of rust-extensions we can remove the revision number from this PR.

We've merged the PR https://github.com/containerd/runwasi/pull/272 that has this functionality, should be able to rebase and remove the custom import

**Comment by Mossaka** [comment]
Need a rebase

**Comment by jsturtevant** [comment]
/lgtm

thanks @vyta 🚀

**Review by Mossaka — APPROVED** [review]

**Comment by jsturtevant** [comment]
> @Mossaka @jsturtevant After rebasing, I am noticing that I'm no longer seeing metrics for `cpuacct.usage`, mem and PIDS ok though. Not sure if this is just an issue I'm seeing w/ my containerd setup or something else?

created #276 so this doesn't get lost

**Pull request merged**
