### PR TITLE
feat(*): remove the network ns in the shim start

### PR DESCRIPTION
**Pull request by Mossaka**
this commit removes the unnecessary nerwork namepsace setup in the shim start function because it is already been set in youki.

See #476

### CODE REVIEW

**Comment by jsturtevant** [comment]
The previous run failed, Did something change?

**Comment by Mossaka** [comment]
> The previous run failed, Did something change?

**Comment by Mossaka** [comment]
1 / 5 runs the CI failed

**Comment by Mossaka** [comment]
timeout error: https://github.com/containerd/runwasi/actions/runs/11864777519/job/33069084169?pr=503#step:7:1001

**Comment by jprendes** [comment]
That timeout error is linked to installing a debian package, so it can be ignored.

**Comment by jprendes** [comment]
@Mossaka , do you ha e a feel from all the runs you did if there are still failures linked to this? If so, what kind of failures? I'm inclined to think that any failures are just the sporadic timeouts we've seen in other places in CI as well.

**Review by jprendes — APPROVED** [review]
LGTM. 
I'm happy with merging this. We csn revert if we notice any issues afterwards.

**Comment by Mossaka** [comment]
> @Mossaka , do you ha e a feel from all the runs you did if there are still failures linked to this? If so, what kind of failures? I'm inclined to think that any failures are just the sporadic timeouts we've seen in other places in CI as well. 

I believe all the failures are related to the sporadic timeouts

**Pull request merged**
